name: Feature request
description: Propose a new chalk-lsp feature or behavior change
body:
  - type: textarea
    attributes:
      label: Summary
      description: |
        A clear and concise description of the relevant request. If applicable, please describe the current behavior as well.
    validations:
      required: true
