[package]
name = "ty_chalk"
version = "0.0.0"
publish = false
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
homepage = { workspace = true }
documentation = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[lib]
doctest = false

[dependencies]
get-size2 = { workspace = true }
ignore = { workspace = true }
ruff_db = { workspace = true }
ruff_memory_usage = { workspace = true }
ruff_python_ast = { workspace = true }
ruff_text_size = { workspace = true }
salsa = { workspace = true }
serde = { workspace = true }
serde_yaml = { workspace = true }
thiserror = { workspace = true }
ty_project = { workspace = true }
ty_python_semantic = { workspace = true }

[dev-dependencies]
ruff_db = { workspace = true, features = ["testing"] }
ty_module_resolver = { workspace = true }
ty_project = { workspace = true, features = ["testing"] }
ty_python_core = { workspace = true }

[lints]
workspace = true
