from typing import Any, Generic, TypeVar, overload

from chalk.features.underscore import Underscore
from chalk.streams import Windowed as _ChalkWindowed

_T_co = TypeVar("_T_co", covariant=True)

class Resolved(Underscore, Generic[_T_co]):
    def __getitem__(self, key: Any) -> Resolved[_T_co]: ...
    def __add__(self, other: _T_co | Resolved[_T_co]) -> Resolved[_T_co]: ...
    def __radd__(self, other: _T_co | Resolved[_T_co]) -> Resolved[_T_co]: ...
    def __sub__(self, other: _T_co | Resolved[_T_co]) -> Resolved[_T_co]: ...
    def __rsub__(self, other: _T_co | Resolved[_T_co]) -> Resolved[_T_co]: ...
    @overload
    def __mul__(self: Resolved[int], other: int | Resolved[int]) -> Resolved[int]: ...
    @overload
    def __mul__(
        self: Resolved[int], other: float | Resolved[float]
    ) -> Resolved[float]: ...
    @overload
    def __mul__(
        self: Resolved[float], other: float | Resolved[int] | Resolved[float]
    ) -> Resolved[float]: ...
    @overload
    def __rmul__(self: Resolved[int], other: int | Resolved[int]) -> Resolved[int]: ...
    @overload
    def __rmul__(
        self: Resolved[int], other: float | Resolved[float]
    ) -> Resolved[float]: ...
    @overload
    def __rmul__(
        self: Resolved[float], other: float | Resolved[int] | Resolved[float]
    ) -> Resolved[float]: ...
    @overload
    def __truediv__(
        self: Resolved[int], other: float | Resolved[int] | Resolved[float]
    ) -> Resolved[float]: ...
    @overload
    def __truediv__(
        self: Resolved[float], other: float | Resolved[int] | Resolved[float]
    ) -> Resolved[float]: ...
    @overload
    def __rtruediv__(
        self: Resolved[int], other: float | Resolved[int] | Resolved[float]
    ) -> Resolved[float]: ...
    @overload
    def __rtruediv__(
        self: Resolved[float], other: float | Resolved[int] | Resolved[float]
    ) -> Resolved[float]: ...
    @overload
    def __floordiv__(
        self: Resolved[int], other: int | Resolved[int]
    ) -> Resolved[int]: ...
    @overload
    def __floordiv__(
        self: Resolved[int], other: float | Resolved[float]
    ) -> Resolved[float]: ...
    @overload
    def __floordiv__(
        self: Resolved[float], other: float | Resolved[int] | Resolved[float]
    ) -> Resolved[float]: ...
    @overload
    def __rfloordiv__(
        self: Resolved[int], other: int | Resolved[int]
    ) -> Resolved[int]: ...
    @overload
    def __rfloordiv__(
        self: Resolved[int], other: float | Resolved[float]
    ) -> Resolved[float]: ...
    @overload
    def __rfloordiv__(
        self: Resolved[float], other: float | Resolved[int] | Resolved[float]
    ) -> Resolved[float]: ...
    def __lt__(self, other: Any) -> Resolved[bool]: ...
    def __le__(self, other: Any) -> Resolved[bool]: ...
    def __gt__(self, other: Any) -> Resolved[bool]: ...
    def __ge__(self, other: Any) -> Resolved[bool]: ...
    def __eq__(self, other: object) -> Resolved[bool]: ...
    def __ne__(self, other: object) -> Resolved[bool]: ...
    def __and__(self, other: _T_co | Resolved[_T_co]) -> Resolved[bool]: ...
    def __rand__(self, other: _T_co | Resolved[_T_co]) -> Resolved[bool]: ...
    def __or__(self, other: _T_co | Resolved[_T_co]) -> Resolved[bool]: ...
    def __ror__(self, other: _T_co | Resolved[_T_co]) -> Resolved[bool]: ...
    def __xor__(self, other: _T_co | Resolved[_T_co]) -> Resolved[bool]: ...
    def __rxor__(self, other: _T_co | Resolved[_T_co]) -> Resolved[bool]: ...
    def __invert__(self) -> Resolved[bool]: ...

class Windowed(Resolved[_T_co], _ChalkWindowed[_T_co], Generic[_T_co]): ...
